### ISSUE TITLE
Error log name different from the actual

### ISSUE THREAD

**Issue by armorik83** [groupon-testium/webdriver-http-sync#20]
https://github.com/groupon-testium/webdriver-http-sync/blob/master/lib/session.js#L12

Hi, I use testium.
webdriver-http-sync said error below when run testium with 'phantomjs'.

```
Uncaught Error: Assertion failed: Failed to start Selenium session. Check the selenium.log.
```

But as it is, testium output log name as 'phantomjs.log'. This is not actual.
It'll be potentially confusing.

Thanks.

**Comment by EndangeredMassa** [comment]
Thanks for the bug report! We'll look into fixing this.
