### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by azu** [groupon-testium/webdriver-http-sync#21]
Hi, I want to implement `Element.prototype.getElement` and  `Element.prototype.getElements`.

```
/session/:sessionId/element/:id/element
/session/:sessionId/element/:id/elements
```

But, this repogitory contain only implementation without tests.  
Related issue: #3 

Do I create the pull-request which is contain only implementation to this repo?
(Additionally, I create the pull-request which is contain only tests to [Testium](https://github.com/groupon-testium/testium "Testium")) 

How to contribute to webdriver-http-sync?

----
Aside:

I think we need these method for using [PageObject](http://martinfowler.com/bliki/PageObject.html "PageObject") pattern.

Real use-case : [Refactoring test by page object by azu · Pull Request #2 · coding-kata/todo-app-jquery-to-backbone](https://github.com/coding-kata/todo-app-jquery-to-backbone/pull/2/files#diff-56f992cd349332e4a12ee4ab62b7b1d4R17 "Refactoring test by page object by azu · Pull Request #2 · coding-kata/todo-app-jquery-to-backbone")

**Comment by EndangeredMassa** [comment]
To test this app, I run the testium test suite linked to the modified webdriver-http-sync code. For now, I'm fine adding tests to testium for changes here. Usually, changes here mean changes in testium anyway. But yes, it would be best if this project had its own test suite.

Page Objects are a fine pattern, but they belong in the applications using testium, exactly as you have already done. I don't know what we can add to testium itself to take advantage of page objects.
